import { Inter } from 'next/font/google'
import './globals.css'
import AddUserClickContextProvider from '@/contexts/AddUserClickContext'
import AddUserContextProvider from '@/contexts/AddUserContext'
import AuthProvider from '@/components/AuthProvider'
import ProtectedRoute from '@/components/ProtectedRoute'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <ProtectedRoute>
    <AddUserClickContextProvider>
      <AddUserContextProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </AddUserContextProvider>
    </AddUserClickContextProvider>
    </ProtectedRoute>
    </AuthProvider>
  )
}
