import { Inter } from 'next/font/google'
import './globals.css'
import AddUserClickContextProvider from '@/contexts/AddUserClickContext'
import AddUserContextProvider from '@/contexts/AddUserContext'
import AuthProvider from '@/components/AuthProvider'
import ProtectedRoute from '@/components/ProtectedRoute'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <ProtectedRoute>
      <AuthProvider>
        <AddUserClickContextProvider>
          <AddUserContextProvider>
            <html lang="en">
              <head>
                <link rel="icon" type="image/svg+xml" sizes='96*96' href="https://img.icons8.com/pulsar-color/96/dashboard.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Board.</title>
              </head>
              <body className={inter.className}>{children}</body>
            </html>
          </AddUserContextProvider>
        </AddUserClickContextProvider>
      </AuthProvider>
    </ProtectedRoute>
  )
}
